# Generated by Django 5.2.17 on 2026-08-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'شهرستان',
                'verbose_name_plural': 'شهرستان\u200cها',
                'ordering': ['province__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_networks', to='organization.county')),
            ],
            options={
                'verbose_name': 'شبکه بهداشت و درمان',
                'verbose_name_plural': 'شبکه\u200cهای بهداشت و درمان',
                'ordering': ['county__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_centers', to='organization.healthnetwork')),
            ],
            options={
                'verbose_name': 'مرکز خدمات جامع سلامت',
                'verbose_name_plural': 'مراکز خدمات جامع سلامت',
                'ordering': ['network__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_province_name')],
            },
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='organization.province'),
        ),
        migrations.CreateModel(
            name='HealthHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_houses', to='organization.healthcenter')),
            ],
            options={
                'verbose_name': 'خانه بهداشت',
                'verbose_name_plural': 'خانه\u200cهای بهداشت',
                'ordering': ['center__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('center', 'name'), name='uniq_house_name_per_center')],
            },
        ),
        migrations.AddConstraint(
            model_name='healthnetwork',
            constraint=models.UniqueConstraint(fields=('county', 'name'), name='uniq_network_name_per_county'),
        ),
        migrations.AddConstraint(
            model_name='healthcenter',
            constraint=models.UniqueConstraint(fields=('network', 'name'), name='uniq_center_name_per_network'),
        ),
        migrations.AddConstraint(
            model_name='county',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='uniq_county_name_per_province'),
        ),
    ]
