# Generated by Django 5.2.17 on 2026-08-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_approval_status_member_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['id'], 'verbose_name': 'عضو', 'verbose_name_plural': 'اعضا'},
        ),
    ]
