# Generated by Django 5.2.17 on 2026-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_status_membershipfee_membershipstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='legal_decree_file',
            field=models.FileField(blank=True, null=True, upload_to='members/legal_decree/%Y/%m/', verbose_name='آخرین حکم کارگزینی'),
        ),
        migrations.AddField(
            model_name='member',
            name='network_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='members/network_letter/%Y/%m/', verbose_name='نامه\u200cی ممهور شبکه بهداشت'),
        ),
    ]
