# Generated by Django 5.2.17 on 2026-09-02 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_legal_decree_file_member_network_letter_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRemovalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('non_payment', 'عدم پرداخت حق عضویت'), ('misconduct', 'توهین یا رفتار نامناسب'), ('disciplinary', 'تخلف انضباطی'), ('other', 'سایر (توضیح در متن)')], max_length=20)),
                ('reason_detail', models.CharField(blank=True, help_text='توضیح تکمیلی (الزامی برای «سایر»)', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تصمیم'), ('approved', 'تأییدشده (عضو حذف شد)'), ('rejected', 'ردشده')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_proposals_decided', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='removal_proposals', to='members.member')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_proposals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشنهاد حذف عضو',
                'verbose_name_plural': 'پیشنهادهای حذف عضو',
                'ordering': ['-created_at'],
            },
        ),
    ]
