# Generated by Django 5.2.17 on 2026-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_memberremovalproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره تماس'),
        ),
    ]
