# Generated by Django 5.2.17 on 2026-09-06 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_mobile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('edit', 'ویرایش'), ('delete', 'حذف')], max_length=10)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('new_due_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500, verbose_name='دلیل درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تصمیم'), ('approved', 'تأییدشده'), ('rejected', 'ردشده')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_change_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='members.membershipfee')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_change_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست اصلاح/حذف حق عضویت',
                'verbose_name_plural': 'درخواست\u200cهای اصلاح/حذف حق عضویت',
                'ordering': ['-created_at'],
            },
        ),
    ]
