# Generated by Django 5.2.17 on 2026-09-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_feechangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدی'), ('bale', 'از طریق بله'), ('card_to_card', 'کارت به کارت')], max_length=50),
        ),
    ]
