# Generated by Django 5.2.17 on 2026-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_membershipfee_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feechangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تصمیم'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('cancelled', 'انصراف داده\u200cشده')], default='pending', max_length=10),
        ),
    ]
