# Generated by Django 5.2.17 on 2026-09-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_normalize_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechangerequest',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fee_change_requests', to='members.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feechangerequest',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='feechangerequest',
            name='original_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feechangerequest',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='members.membershipfee'),
        ),
    ]
