# Generated by Django 5.2.17 on 2026-09-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_feechangerequest_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='national_id_card_file',
            field=models.ImageField(blank=True, null=True, upload_to='members/national_id/%Y/%m/', verbose_name='تصویر کارت ملی'),
        ),
        migrations.CreateModel(
            name='MemberBirthCertificatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='members/birth_certificate/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_certificate_pages', to='members.member')),
            ],
            options={
                'verbose_name': 'تصویر صفحه\u200cی شناسنامه',
                'verbose_name_plural': 'تصاویر صفحات شناسنامه',
                'ordering': ['created_at'],
            },
        ),
    ]
