# Generated by Django 5.2.17 on 2026-09-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_member_documents_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_certificate_rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='legal_decree_rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='national_id_rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='network_letter_rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
