# Generated by Django 5.2.17 on 2026-09-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_member_birth_certificate_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_certificate_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='legal_decree_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='national_id_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='network_letter_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
