# Generated by Django 5.2.17 on 2026-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_member_birth_certificate_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='service_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع به خدمت بهورزی'),
        ),
    ]
