# Generated by Django 5.2.17 on 2026-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_of_birth_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, help_text='این نام به\u200cجای نام کاربری برای دیگران نمایش داده می\u200cشود؛ کلید ورود نیست.', max_length=50, null=True, unique=True, verbose_name='نام نمایشی'),
        ),
    ]
