# Generated by Django 5.2.17 on 2026-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='در اولین ورود، کاربر مجبور به تغییر رمز عبور خود می\u200cشود.', verbose_name='الزام تغییر رمز عبور'),
        ),
    ]
