# Generated by Django 5.2.17 on 2026-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0002_tag_remove_newsarticle_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
