# Generated by Django 5.2.17 on 2026-09-04 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0003_newsarticle_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='public_content/document_files/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='حجم فایل به بایت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='public_content.publicdocument')),
            ],
            options={
                'verbose_name': 'فایل پیوست سند',
                'verbose_name_plural': 'فایل\u200cهای پیوست سند',
                'ordering': ['created_at'],
            },
        ),
    ]
