# Generated by Django 5.2.17 on 2026-09-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_content', '0004_publicdocumentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicdocument',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='documents_multi', to='public_content.documentcategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
    ]
