# Generated by Django 5.2.17 on 2026-08-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('chairman', 'رئیس'), ('vice_chairman', 'نایب رئیس'), ('treasurer', 'خزانه\u200cدار'), ('secretary', 'دبیر'), ('member', 'عضو')], db_index=True, max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_memberships_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضویت هیئت\u200cمدیره',
                'verbose_name_plural': 'عضویت\u200cهای هیئت\u200cمدیره',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='board_membership_end_after_start'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uniq_active_board_membership_per_user'), models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('position', 'member'), _negated=True)), fields=('position',), name='uniq_active_unique_board_position')],
            },
        ),
    ]
