# Generated by Django 5.2.17 on 2026-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='is_public_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این عضویت در صفحه\u200cی عمومی هیئت\u200cمدیره نمایش داده شود؟'),
        ),
    ]
