# Generated by Django 5.2.17 on 2026-08-30 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardmembership_is_public_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('archived', 'بایگانی\u200cشده')], db_index=True, default='draft', max_length=20)),
                ('is_public_visible', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دوره\u200cی هیئت\u200cمدیره',
                'verbose_name_plural': 'دوره\u200cهای هیئت\u200cمدیره',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='board_end_after_start')],
            },
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='board.board'),
        ),
        migrations.CreateModel(
            name='BoardStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('archived', 'بایگانی\u200cشده')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('archived', 'بایگانی\u200cشده')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_status_changes', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='board.board')),
            ],
            options={
                'verbose_name': 'تاریخچه\u200cی وضعیت هیئت\u200cمدیره',
                'verbose_name_plural': 'تاریخچه\u200cهای وضعیت هیئت\u200cمدیره',
                'ordering': ['-created_at'],
            },
        ),
    ]
