# Generated by Django 5.2.17 on 2026-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_boardmembership_board_boardstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='service_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع به خدمت بهورزی'),
        ),
    ]
