# Generated by Django 5.2.17 on 2026-08-23 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('behvarz', 'بهورز'), ('assistant', 'کمک\u200cبهورز'), ('other', 'سایر')], default='behvarz', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('health_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_assignments', to='organization.healthhouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تخصیص محل خدمت',
                'verbose_name_plural': 'تخصیص\u200cهای محل خدمت',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='employment_end_after_start'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('user',), name='uniq_active_primary_employment_per_user')],
            },
        ),
    ]
