# Generated by Django 5.2.17 on 2026-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_public_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این کمیته در صفحه\u200cی عمومی کمیته\u200cها نمایش داده شود؟'),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='is_public_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این عضویت در صفحه\u200cی عمومی کمیته نمایش داده شود؟'),
        ),
    ]
