# Generated by Django 5.2.17 on 2026-08-30 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_accessscope_committee'),
        ('committees', '0002_committee_is_public_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='scope',
            field=models.ForeignKey(blank=True, help_text='محدوده\u200cی سازمانی خود کمیته (استان/شهرستان) — مستقل از Scope تخصیص نقش\u200cها', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='authorization.accessscope'),
        ),
        migrations.AddField(
            model_name='committee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('archived', 'بایگانی\u200cشده')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CommitteeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('archived', 'بایگانی\u200cشده')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('archived', 'بایگانی\u200cشده')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_status_changes', to=settings.AUTH_USER_MODEL)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='committees.committee')),
            ],
            options={
                'verbose_name': 'تاریخچه\u200cی وضعیت کمیته',
                'verbose_name_plural': 'تاریخچه\u200cهای وضعیت کمیته',
                'ordering': ['-created_at'],
            },
        ),
    ]
