# Generated by Django 5.2.17 on 2026-08-31 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_seed_board_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0002_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 فایل', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='scope',
            field=models.ForeignKey(blank=True, help_text='محدوده\u200cی سازمانی سند (استان/شهرستان/شبکه/مرکز/خانه/کمیته)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='authorization.accessscope'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('review', 'در حال بررسی'), ('approved', 'تأییدشده'), ('published', 'منتشرشده'), ('archived', 'بایگانی\u200cشده')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('private', 'خصوصی'), ('internal', 'داخلی'), ('restricted', 'محدود'), ('public', 'عمومی')], db_index=True, default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('review', 'در حال بررسی'), ('approved', 'تأییدشده'), ('published', 'منتشرشده'), ('archived', 'بایگانی\u200cشده')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('review', 'در حال بررسی'), ('approved', 'تأییدشده'), ('published', 'منتشرشده'), ('archived', 'بایگانی\u200cشده')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_status_changes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='documents.document')),
            ],
            options={
                'verbose_name': 'تاریخچه\u200cی وضعیت سند',
                'verbose_name_plural': 'تاریخچه\u200cهای وضعیت سند',
                'ordering': ['-created_at'],
            },
        ),
    ]
