server {
    listen 80;
    server_name behvarzan-mazandaran.ir www.behvarzan-mazandaran.ir;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name behvarzan-mazandaran.ir www.behvarzan-mazandaran.ir;

    ssl_certificate /etc/letsencrypt/live/behvarzan-mazandaran.ir/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/behvarzan-mazandaran.ir/privkey.pem;

    client_max_body_size 10M;

    location /static/ {
        alias /var/www/behvarzan_site/staticfiles/;
    }

    location /media/ {
        alias /var/www/behvarzan_site/media/;
    }

    location / {
        proxy_pass http://unix:/run/behvarzan_site.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}