# Generated by Django 5.2.17 on 2026-08-31 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0012_seed_request_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('membership', 'درخواست عضویت'), ('membership_renewal', 'تمدید عضویت'), ('employment_transfer', 'تغییر محل خدمت'), ('employment_update', 'اصلاح اطلاعات محل خدمت'), ('role_assignment', 'تخصیص نقش انجمنی'), ('role_revocation', 'لغو نقش انجمنی'), ('committee', 'درخواست مربوط به کمیته'), ('board', 'درخواست مربوط به هیئت\u200cمدیره'), ('document', 'درخواست مربوط به اسناد'), ('profile_update', 'اصلاح اطلاعات پروفایل'), ('other', 'سایر')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('under_review', 'در حال بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('returned', 'برگشت\u200cداده\u200cشده'), ('resubmitted', 'ثبت\u200cمجدد'), ('cancelled', 'لغوشده'), ('completed', 'تکمیل\u200cشده')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_approved', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_created', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(blank=True, help_text='محدوده\u200cی سازمانی درخواست (برای Scope-aware Authorization مدیران)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='authorization.accessscope')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('under_review', 'در حال بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('returned', 'برگشت\u200cداده\u200cشده'), ('resubmitted', 'ثبت\u200cمجدد'), ('cancelled', 'لغوشده'), ('completed', 'تکمیل\u200cشده')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت\u200cشده'), ('under_review', 'در حال بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده'), ('returned', 'برگشت\u200cداده\u200cشده'), ('resubmitted', 'ثبت\u200cمجدد'), ('cancelled', 'لغوشده'), ('completed', 'تکمیل\u200cشده')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='requests.request')),
            ],
            options={
                'verbose_name': 'تاریخچه\u200cی وضعیت درخواست',
                'verbose_name_plural': 'تاریخچه\u200cهای وضعیت درخواست',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['requester', 'status'], name='requests_re_request_100d86_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['request_type', 'status'], name='requests_re_request_449831_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['content_type', 'object_id'], name='requests_re_content_9605bf_idx'),
        ),
    ]
