# Generated by Django 5.2.17 on 2026-09-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forumcomment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumLastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_seen_records', to='forums.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_last_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آخرین بازدید فروم',
                'verbose_name_plural': 'آخرین بازدیدهای فروم',
                'constraints': [models.UniqueConstraint(fields=('user', 'forum'), name='uniq_last_seen_per_user_per_forum')],
            },
        ),
    ]
