# Generated by Django 5.2.17 on 2026-08-25 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('national_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('workplace_note', models.CharField(blank=True, help_text='نام خانه بهداشت یا مرکز محل خدمت (به\u200cصورت متنی)', max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_applications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست عضویت',
                'verbose_name_plural': 'درخواست\u200cهای عضویت',
                'ordering': ['-created_at'],
            },
        ),
    ]
