# Generated by Django 5.2.17 on 2026-08-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='message',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='workplace_note',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='پذیرش تعهدنامه'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='health_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_applications', to='organization.healthhouse', verbose_name='خانه بهداشت محل خدمت'),
        ),
    ]
