# Generated by Django 5.2.17 on 2026-09-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_membershipapplication_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='legal_decree_file',
            field=models.FileField(default=' ', upload_to='membership_applications/legal_decree/%Y/%m/', verbose_name='آخرین حکم کارگزینی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='network_letter_file',
            field=models.FileField(default='', upload_to='membership_applications/network_letter/%Y/%m/', verbose_name='نامه\u200cی ممهور شبکه بهداشت'),
            preserve_default=False,
        ),
    ]
