# Generated by Django 5.2.17 on 2026-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_membershipapplication_legal_decree_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='legal_decree_file',
            field=models.FileField(blank=True, null=True, upload_to='membership_applications/legal_decree/%Y/%m/', verbose_name='آخرین حکم کارگزینی'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='network_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='membership_applications/network_letter/%Y/%m/', verbose_name='نامه\u200cی ممهور شبکه بهداشت'),
        ),
    ]
