# Generated by Django 5.2.17 on 2026-08-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_seed_permissions_and_roles'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessscope',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_scopes', to='organization.healthcenter'),
        ),
        migrations.AddField(
            model_name='accessscope',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_scopes', to='organization.county'),
        ),
        migrations.AddField(
            model_name='accessscope',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_scopes', to='organization.healthhouse'),
        ),
        migrations.AddField(
            model_name='accessscope',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_scopes', to='organization.healthnetwork'),
        ),
        migrations.AddField(
            model_name='accessscope',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_scopes', to='organization.province'),
        ),
    ]
