# Generated by Django 5.2.17 on 2026-08-29 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def fix_historical_status(apps, schema_editor):
    RoleAssignment = apps.get_model("authorization", "RoleAssignment")
    RoleAssignment.objects.filter(is_active=False).exclude(status="rejected").update(status="ended")

def reverse_fix_historical_status(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_seed_membership_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='status',
            field=models.CharField(choices=[('proposed', 'پیشنهادشده'), ('pending_approval', 'در انتظار تأیید'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('revoked', 'لغوشده (اجباری)'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده (داوطلبانه)')], db_index=True, default='active', help_text='چرخه\u200cی عملیاتی تخصیص (Proposed→Active→Ended/Revoked) — مستقل از approval_status', max_length=20),
        ),
        migrations.CreateModel(
            name='RoleAssignmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('proposed', 'پیشنهادشده'), ('pending_approval', 'در انتظار تأیید'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('revoked', 'لغوشده (اجباری)'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده (داوطلبانه)')], max_length=20)),
                ('new_status', models.CharField(choices=[('proposed', 'پیشنهادشده'), ('pending_approval', 'در انتظار تأیید'), ('active', 'فعال'), ('suspended', 'معلق'), ('ended', 'پایان\u200cیافته'), ('revoked', 'لغوشده (اجباری)'), ('rejected', 'ردشده'), ('cancelled', 'لغوشده (داوطلبانه)')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('role_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='authorization.roleassignment')),
            ],
            options={
                'verbose_name': 'تاریخچه\u200cی وضعیت تخصیص نقش',
                'verbose_name_plural': 'تاریخچه\u200cهای وضعیت تخصیص نقش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(fix_historical_status, reverse_fix_historical_status),
    ]
