# Generated by Django 5.2.17 on 2026-08-30 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_roleassignment_status_roleassignmentstatushistory'),
        ('committees', '0002_committee_is_public_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessscope',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_scopes', to='committees.committee'),
        ),
    ]
