# Generated by Django 5.2.17 on 2026-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_seed_committee_permissions_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='is_public_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این تخصیص نقش (مثلاً نمایندگی) در سایت عمومی نمایش داده شود؟'),
        ),
    ]
